# Config format schema number
format_version: 7

###################
## Model options
model_params:
  history_num_frames_ego: 1  # this will also create raster history (we need to remove the raster from train/eval dataset - only visualization)
  history_num_frames: 0
  history_num_frames_agents: 1
  step_time: 0.1
  future_num_frames: 248  # 248 is the amount of simulation steps per scene.

val_data_loader:
  key: "scenes/validate_0.zarr"

raster_params:
  # the keys are relative to the dataset environment variable
  semantic_map_key: "semantic_map/semantic_map.pb"
  dataset_meta_key: "meta.json"

  # e.g. 0.0 include every obstacle, 0.5 show those obstacles with >0.5 probability of being
  # one of the classes we care about (cars, bikes, peds, etc.), >=1.0 filter all other agents.
  filter_agents_threshold: 0.5

  # whether to completely disable traffic light faces in the semantic rasterizer
  # this disable option is not supported in avsw_semantic
  disable_traffic_light_faces: False

###################
## VectorNet Params
data_generation_params:
  # maximum number of other agents to take (if less will be padded)
  other_agents_num: 30
  # maximum distance from AoI for another agent to be picked
  max_agents_distance: 35

  traffic_light_faces_num: 20
